name: "01 - Building Blocks"
on: "push, workflow_dispatch"

jobs:
  echo-hello: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
        name:"Say hello"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I"
          echo "will fail"
        name: "Failed step"
      
      - run: echo "Goodbye!"
        name: "Say Goodbye"
