name: "02 - Workflow Events"
on: 
- push
- pull_request
- schedule
  - cron:'*/10 * * * *'
- workflow_dispatch
jobs:
    echo: 
      runs-on: ubuntu-latest
      steps:
        - run: |
              echo "Event name: ${{ github.event_name }}"
          name: "Show the trigger"
